//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 11:42:12 AM CLST 
//


package cl.cc.rfms.entity.response.position;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VehiclePosition" type="{http://fms-standard.com/rfms/v1.0.0/xsd/position}VehiclePositionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MoreDataAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="RequestServerDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehiclePosition",
    "moreDataAvailable",
    "requestServerDateTime"
})
@XmlRootElement(name = "VehiclePositionResponse")
public class VehiclePositionResponse {

    @XmlElement(name = "VehiclePosition")
    protected List<VehiclePositionType> vehiclePosition;
    @XmlElement(name = "MoreDataAvailable")
    protected boolean moreDataAvailable;
    @XmlElement(name = "RequestServerDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestServerDateTime;

    /**
     * Gets the value of the vehiclePosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehiclePosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehiclePosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehiclePositionType }
     * 
     * 
     */
    public List<VehiclePositionType> getVehiclePosition() {
        if (vehiclePosition == null) {
            vehiclePosition = new ArrayList<VehiclePositionType>();
        }
        return this.vehiclePosition;
    }

    /**
     * Gets the value of the moreDataAvailable property.
     * 
     */
    public boolean isMoreDataAvailable() {
        return moreDataAvailable;
    }

    /**
     * Sets the value of the moreDataAvailable property.
     * 
     */
    public void setMoreDataAvailable(boolean value) {
        this.moreDataAvailable = value;
    }

    /**
     * Gets the value of the requestServerDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestServerDateTime() {
        return requestServerDateTime;
    }

    /**
     * Sets the value of the requestServerDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestServerDateTime(XMLGregorianCalendar value) {
        this.requestServerDateTime = value;
    }

}
