//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 11:39:28 AM CLST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fms-standard.com/rfms/v1.0.0/xsd/list", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cl.cc.rfms.entity.response.list;
