//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 11:42:42 AM CLST 
//


package cl.cc.rfms.entity.response.status;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DriverWorkingStateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DriverWorkingStateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Rest"/>
 *     &lt;enumeration value="Driver available"/>
 *     &lt;enumeration value="Work"/>
 *     &lt;enumeration value="Drive"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Not available"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DriverWorkingStateType")
@XmlEnum
public enum DriverWorkingStateType {

    @XmlEnumValue("Rest")
    REST("Rest"),
    @XmlEnumValue("Driver available")
    DRIVER_AVAILABLE("Driver available"),
    @XmlEnumValue("Work")
    WORK("Work"),
    @XmlEnumValue("Drive")
    DRIVE("Drive"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("Not available")
    NOT_AVAILABLE("Not available");
    private final String value;

    DriverWorkingStateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DriverWorkingStateType fromValue(String v) {
        for (DriverWorkingStateType c: DriverWorkingStateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
