//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 11:42:42 AM CLST 
//


package cl.cc.rfms.entity.response.status;

import cl.cc.rfms.entity.response.position.GNSSPositionType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VehicleStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VIN" type="{http://fms-standard.com/rfms/v1.0.0/xsd/common/vehicle}VinType"/>
 *         &lt;element name="TriggerType" type="{http://fms-standard.com/rfms/v1.0.0/xsd/common/trigger}TriggerType"/>
 *         &lt;element name="CreatedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ReceivedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="GNSSPosition" type="{http://fms-standard.com/rfms/v1.0.0/xsd/common/position}GNSSPositionType"/>
 *         &lt;element name="WheelBasedSpeed" type="{http://fms-standard.com/rfms/v1.0.0/xsd/common/position}SpeedType"/>
 *         &lt;element name="TachographSpeed" type="{http://fms-standard.com/rfms/v1.0.0/xsd/common/position}SpeedType" minOccurs="0"/>
 *         &lt;element name="HRTotalVehicleDistance" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}HighResolutionTotalVehicleDistanceType"/>
 *         &lt;element name="EngineTotalFuelUsed" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}EngineTotalFuelUsedType"/>
 *         &lt;element name="FuelLevel1" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}FuelLevel1Type"/>
 *         &lt;element name="CatalystFuelLevel" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}CatalystFuelLevelType" minOccurs="0"/>
 *         &lt;element name="GrossCombinationVehicleWeight" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}GrossCombinationVehicleWeightType" minOccurs="0"/>
 *         &lt;element name="Driver1" type="{http://fms-standard.com/rfms/v1.0.0/xsd/status}DriverType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleStatusType", propOrder = {
    "vin",
    "triggerType",
    "createdDateTime",
    "receivedDateTime",
    "gnssPosition",
    "wheelBasedSpeed",
    "tachographSpeed",
    "hrTotalVehicleDistance",
    "engineTotalFuelUsed",
    "fuelLevel1",
    "catalystFuelLevel",
    "grossCombinationVehicleWeight",
    "driver1"
})
public class VehicleStatusType {

    @XmlElement(name = "VIN", required = true)
    protected String vin;
    @XmlElement(name = "TriggerType", required = true)
    @XmlSchemaType(name = "string")
    protected TriggerType triggerType;
    @XmlElement(name = "CreatedDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    @XmlElement(name = "ReceivedDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar receivedDateTime;
    @XmlElement(name = "GNSSPosition", required = true)
    protected GNSSPositionType gnssPosition;
    @XmlElement(name = "WheelBasedSpeed")
    protected double wheelBasedSpeed;
    @XmlElement(name = "TachographSpeed")
    protected Double tachographSpeed;
    @XmlElement(name = "HRTotalVehicleDistance")
    protected double hrTotalVehicleDistance;
    @XmlElement(name = "EngineTotalFuelUsed")
    protected double engineTotalFuelUsed;
    @XmlElement(name = "FuelLevel1")
    protected double fuelLevel1;
    @XmlElement(name = "CatalystFuelLevel")
    protected Double catalystFuelLevel;
    @XmlElement(name = "GrossCombinationVehicleWeight")
    @XmlSchemaType(name = "integer")
    protected Integer grossCombinationVehicleWeight;
    @XmlElement(name = "Driver1", required = true)
    protected DriverType driver1;

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIN() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIN(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerType }
     *     
     */
    public TriggerType getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerType }
     *     
     */
    public void setTriggerType(TriggerType value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the receivedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedDateTime() {
        return receivedDateTime;
    }

    /**
     * Sets the value of the receivedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedDateTime(XMLGregorianCalendar value) {
        this.receivedDateTime = value;
    }

    /**
     * Gets the value of the gnssPosition property.
     * 
     * @return
     *     possible object is
     *     {@link GNSSPositionType }
     *     
     */
    public GNSSPositionType getGNSSPosition() {
        return gnssPosition;
    }

    /**
     * Sets the value of the gnssPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link GNSSPositionType }
     *     
     */
    public void setGNSSPosition(GNSSPositionType value) {
        this.gnssPosition = value;
    }

    /**
     * Gets the value of the wheelBasedSpeed property.
     * 
     */
    public double getWheelBasedSpeed() {
        return wheelBasedSpeed;
    }

    /**
     * Sets the value of the wheelBasedSpeed property.
     * 
     */
    public void setWheelBasedSpeed(double value) {
        this.wheelBasedSpeed = value;
    }

    /**
     * Gets the value of the tachographSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTachographSpeed() {
        return tachographSpeed;
    }

    /**
     * Sets the value of the tachographSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTachographSpeed(Double value) {
        this.tachographSpeed = value;
    }

    /**
     * Gets the value of the hrTotalVehicleDistance property.
     * 
     */
    public double getHRTotalVehicleDistance() {
        return hrTotalVehicleDistance;
    }

    /**
     * Sets the value of the hrTotalVehicleDistance property.
     * 
     */
    public void setHRTotalVehicleDistance(double value) {
        this.hrTotalVehicleDistance = value;
    }

    /**
     * Gets the value of the engineTotalFuelUsed property.
     * 
     */
    public double getEngineTotalFuelUsed() {
        return engineTotalFuelUsed;
    }

    /**
     * Sets the value of the engineTotalFuelUsed property.
     * 
     */
    public void setEngineTotalFuelUsed(double value) {
        this.engineTotalFuelUsed = value;
    }

    /**
     * Gets the value of the fuelLevel1 property.
     * 
     */
    public double getFuelLevel1() {
        return fuelLevel1;
    }

    /**
     * Sets the value of the fuelLevel1 property.
     * 
     */
    public void setFuelLevel1(double value) {
        this.fuelLevel1 = value;
    }

    /**
     * Gets the value of the catalystFuelLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCatalystFuelLevel() {
        return catalystFuelLevel;
    }

    /**
     * Sets the value of the catalystFuelLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCatalystFuelLevel(Double value) {
        this.catalystFuelLevel = value;
    }

    /**
     * Gets the value of the grossCombinationVehicleWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossCombinationVehicleWeight() {
        return grossCombinationVehicleWeight;
    }

    /**
     * Sets the value of the grossCombinationVehicleWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossCombinationVehicleWeight(Integer value) {
        this.grossCombinationVehicleWeight = value;
    }

    /**
     * Gets the value of the driver1 property.
     * 
     * @return
     *     possible object is
     *     {@link DriverType }
     *     
     */
    public DriverType getDriver1() {
        return driver1;
    }

    /**
     * Sets the value of the driver1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DriverType }
     *     
     */
    public void setDriver1(DriverType value) {
        this.driver1 = value;
    }

}
